### ISSUE TITLE
Input : Unhandled Text - Hodor Bot

### ISSUE THREAD

**Issue by JohnGreco** [chrispanag/ebony#2]
**Output** : 
(node:6373) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'entities' of undefined
    at /home/parparelis/ebony/lib/handlers/nlp.js:10:17
    at /home/parparelis/ebony/lib/handlers/text.js:16:16
    at getContext.then.messaging (/home/parparelis/ebony/lib/webhooks/messaging.js:37:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:6373) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6373) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by chrispanag** [comment]
This has a temporary fix now :) We'll need to add a fallback text reply eventually.
